apiVersion: v1
kind: Namespace
metadata:
  name: account-service

---
apiVersion: v1
kind: Service
metadata:
  name: ac-svc
  namespace: account-service
spec:
  ports:
  - port: 80
    targetPort: 8070
  selector:
    app: ac-pod
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ac-pod
  namespace: account-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ac-pod
  template:
    metadata:
      labels:
        app: ac-pod
    spec:
      containers:
      - image: 922416659900.dkr.ecr.us-east-1.amazonaws.com/terraformcreate:latest
        name: ac-pod
        imagePullPolicy: Always
        resources: {}
        ports:
          - containerPort: 8070
